### ISSUE TITLE
lein cljsbuild once =>  Could not locate om_tools/dom__init.class or om_tools/dom.clj on classpath

### ISSUE THREAD

**Issue by tangrammer** [Prismatic/om-tools#72]
Hi Folks, 
Does anyone have this error too?
I just cloned the repo and did `lein cljsbuild once`

```
lein cljsbuild once
Compiling ClojureScript.
Compiling "target/test.js" from ["src" "test" "target/generated/src"]...
WARNING: unsigned-bit-shift-right already refers to: #'clojure.core/unsigned-bit-shift-right in namespace: cljs.core, being replaced by: #'cljs.core/unsigned-bit-shift-right
Compiling "target/test.js" failed.
clojure.lang.ExceptionInfo: Could not locate om_tools/dom__init.class or om_tools/dom.clj on classpath:  at line 1  {:tag :cljs/analysis-error, :file nil, :line 1, :column 1}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at cljs.analyzer$error.invoke(analyzer.clj:267)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1415)
	at cljs.analyzer$analyze$fn__1623.invoke(analyzer.clj:1506)
...
```

Thanks!

**Comment by loganlinn** [comment]
Try running 'lein cljx once' first. It should probably be configured in the
project.clj to be automatic, butdoesn't  sound like it is.

**Comment by tangrammer** [comment]
:+1: 
thanks!
